spring.application.name=ms-eureka
#server.port=8761 nos permite establecer el puerto que usara el ms-eureka
server.port=8761
#eureka.client.register-with-eureka=false lo utilizamos para decirle a eureka que no debe
#intentar conectarse a ningun servidor, le decimos que el es el servidor
eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false le decimos a eureka que no debe estar buscando 
#obtener su propio registro
eureka.client.fetch-registry=false
#eureka.instance.hostname=localhost lo utilizamos para que eureka no busque la direccion ip
#del dispositivo y se registre utilizando localhost
eureka.instance.hostname=localhost